export const AUTH_LOADING = "AUTH_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOGOUT_USER = "LOGOUT_USER";
